name: Update Detections To Elastic

on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
      - uses: jitterbit/get-changed-files@v1
      - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
        