name: Update Detections To Elastic

on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
  - name: Get changes
    run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
        