name: Update Detections To Elastic

on:
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
